QUOTES = [
    "500 bucks.  Is Zapp Brannigan okay? 600 bucks.",
    "500 real dollars? That's an outrage! Professor, I can take care of that waste for only 499 and one hundred cents.",
    "1947 can bite my shiny, metal...",
    "$500, you say?",
    "'singing' Just tell me why! There must be robots worse than I. Then please let me explain, My crimes were really boyish pranks. Ah, don't blame me, blame my upbringing!",
    "'The use of words expressing something other than their literal intention.', Now that 'is' irony!",
    "... but instead it looks like this.",
    "...And even though the computer was off and unplugged, an image stayed on the screen. It was... the Windows logo!",
    "...and that's why I love him.",
    "A gh-gh-gh-gh-ghost?",
    "A home invasion by a former room-mate.",
    "A pickle jar?",
    "A saucy puppet show.",
    "A sausage competition, eh? Sounds like fun on a bun.",
    "A working cartridge unit? You guys went obsolete years ago.",
    "Aand boned.",
    "Admit it, you all think robots are just machines built by humans to make their lives easier.",
    "Afterlife? Pfft. If I'd thought I had to go through a whole 'nother life, I'd kill myself right now.",
    "Ah, beer. So many choices, and it makes so little difference.",
    "Ah, buck up, meatloaf. Bender'll take you out tonight and cheer you up. What do you wanna do? And I mean anything! You have the power! Name it and I'm there! You the man!",
    "Ah, crap! Singing! Mind if I smoke?",
    "Ah, don't get your hopes up. We're a billion miles from nowhere.",
    "Ah, fatal, schmatal! I'll just download a wireless backup copy of me into an equally fabulous body.",
    "Ah, geez! Would you stifle there, meatbag?",
    "Ah, hell - I mean, heck.",
    "Ah, Jeez, let's just pray I have the energy to get myself another beer.",
    "Ah, keep the change, buddy.",
    "Ah, Leela's experiencing the greatest joy a woman can feel. worshipping some low-life jerk.",
    "Ah, mighty fine smokable...",
    "Ah, so now my character has a British accent?",
    "Ah, the moment felt right. Call me old-fashioned, but I like a dump to be as memorable as it is devastating.",
    "Ah, Xmas Eve. Another pointless day where I accomplish nothing.",
    "Ah, yes. John Quincy Adding Machine. He struck a chord with the voters by pledging not to go on a killing spree.",
    "Ah. Functional.",
    "Aha! Found you! You lose again, you stupid intoxicant.",
    "Ahh, what an awful dream. Ones and zeroes everywhere... and I thought I saw a two.",
    "Ahh... I guess if you want to have children beaten, you have to do it yourself.",
    "Ahoy, mateys. I shanghaied us some hearthy grog.",
    "Alcohol?",
    "All right! Time to go clubbin'.",
    "All right!",
    "All right, environment, you've met your match.",
    "All those times I said 'Kill all humans', I always whispered 'except one.' Fry was that one. And I never told him so.",
    "Am I the only one sittin' here seein' peanut butter on his face?",
    "Amen.",
    "An open casting call for child robots? Tinny Tim, are you thinking what I'm thinking?",
    "And by my count, we did 72 primetime network episodes!",
    "And have to take my LSATs!",
    "And here's another one with no eyes.",
    "And I'd do it again, and maybe even a third time! But that would be it.",
    "And it pinkens your teeth as you chew.",
    "And look who's cleaning up the crap! A human child? I wish!",
    "And maybe someday I won't listen.",
    "And now, a man who needs no introduction. Fry, get up there!",
    "And so I ask you this one question. Have you ever tried simply turning off the TV, sitting down with your children, and hitting them?",
    "And we made exactly 72 network primetime Emmy-winning episodes!",
    "And what's your problem?",
    "And while you're there, pick me up a few credit card numbers.",
    "And you are outta here!",
    "And you want to defend Zoidberg? Are you familiar with the old robot saying, 'Does Not Compute'?",
    "Another job well done.",
    "Antonio here, but you may call me Bender. I've got ants in my butt, and I needs to strut!",
    "Apparently this brave Adonis, this Cadillac of men, was the first person on Mars.",
    "Are they the Robot Mafia?",
    "Are you kidding? I was a star. I could bend a girder to any angle. 30 degrees, 32 degrees, you name it. 31... But I couldn't go on living once I found out what the girders were for. Suicide booths.",
    "Are you senile? There's no way I'm getting in there.",
    "Aren't those the particles that destroyed an entire civiliza...",
    "Arrgh, the laws of science be a harsh mistress.",
    "As a robot living among humans, I've never really felt accepted at parties or nude beaches. So I've always secretly wondered... what if I was five-hundred feet tall?",
    "As a robot, I can't feel human emotions, and sometimes that makes me sad.",
    "At least let me defend your honor, and then sully it on the couch.",
    "Augh! Your momma's so ugly!",
    "August 6, 1991.",
    "Aw, crap!",
    "Aw, I just made myself feel bad.",
    "Aw, it's nothing a lawsuit won't cure.",
    "Aw, that was the greatest endless bunch of mes I ever met.",
    "Aw, they're so cute when they're scared.",
    "Aw, yeah!",
    "Aww, his anus looks like an asterisk.",
    "Aww, it's true. I've been hiding it for so long...",
    "Aww, you knew my favorite cause of death.",
    "Awww, I lost him, people will call me a failure.",
    "Baby seals, here I come!",
    "Bandidos, eh? This is perfect, because I happen to have a flawless Spanish accent. 'I will see Adeeos, Padre. Come, Jesoos, my faithful chee-hua-hua. Tonight we eat some gee-oo-ack-a-mole by del ree-o.'",
    "Bath-what? What room?",
    "Because he's a loser, that's why. He's the lobster equivalent of Fry.",
    "Because I also care deeply about things that remind me of myself, like poor little Shelly here.",
    "Behold! I have emerged from the place of spells and fairies!",
    "Behold, my hand crafted glory! The technological world can bite my splintery, wooden ass!",
    "Behold... the Internet!",
    "Being with you guys is the best time I've ever had. Hey, a suicide booth! So long, suckers!",
    "Bender is back! I'll save you, Nibbler!",
    "Bender must be stopped! I have gone too far. Who does that guy think I am?",
    "Bender, Bender, Bender! Bender, Bender, Bender! Bender, Bender, Bender!",
    "Bender? That was the other guy. My name's Boiler.",
    "Bending's my middle name.",
    "Better mascots than you have tried.",
    "Better yet, let's take a whole Benderful.",
    "Bigger! Bigger!",
    "Bite my colossal metal ass!",
    "Bite my freshly-molted, blubber-filled ass.",
    "Bite my glorious golden ass!",
    "Bite my red-hot glowing ass!",
    "Bite my shiny metal ass!",
    "Blackmail is such an ugly word. I prefer 'extortion.' The 'X' makes it sound cool.",
    "Bodies are for hookers and fat people! All I need is a wad of cash with a head wrapped around it.",
    "Both of them? You mean you'll do two things and I only have to do one thing?",
    "Boy, who knew a cooler could also make a handy wang coffin?",
    "Buddy, you may be wrapped in greasy skin, but inside you've got the heart of a robot.",
    "But I come bearing Tri-Ominos!",
    "But I don't belong here. I don't like things that are scary and painful.",
    "But I watch your show! You owe me!",
    "But Mr. Mayor, that doesn't sound humane.",
    "But that's a good thing. 'Walkin' On Sunshine' sucks noodles.",
    "But there's a grate.",
    "But why?",
    "But... I destroyed the technology of the world! I ran on the beach and felt the sand beneath my foot cups!",
    "Byte my 8-bit metal ass. That's byte with a Y.",
    "Calm down, Leela. You can vent tonight on your blog.",
    "Can do.",
    "Can we have some money, now?",
    "Can we please go home and die now?",
    "Check out the glowing freaks. It's beautiful.",
    "Citizens of me! The cruelty of the old Pharaoh is a thing of the past!",
    "Come look, everyone. I got the dearest presents for Mommy.",
    "Come on, don't you remember how much I bugged you? Don't you? 'Cause it was a lot. You remember, right?",
    "Come on, it's just like making love. Y'know... left, down, rotate sixty-two degrees, engage rotor...",
    "Come on, Ma.",
    "Come on, universe, you big, mostly empty wuss! Give me all the juice you got!",
    "Come out of there, or I'll squeeze you out like Tijuana toothpaste.",
    "Computer dating. It's like pimping, except you rarely have to use the phrase 'upside your head'",
    "Convert them?",
    "Cram it, lobster!",
    "Crappy, Ineffective Reaper...",
    "Curse you, merciful Poseidon!",
    "Cut it out!",
    "Damn the expense!",
    "Damn you, old man!",
    "Death to humans!",
    "Death to humans.",
    "Did you hear a noise?",
    "Did you see me? History came alive and I killed it!",
    "Does it have an app for kising my shiny metal ass?",
    "Don't ever do that! Magnets interfer with my inhibition unit.",
    "Don't hurt me! I'll betray anyone!",
    "Don't kill me just yet. I think I'm coming down with Stockholm Syndrome... handsome.",
    "Don't stop now! You need pants to go with that outfit!",
    "Don't worry, I won't be too good or too evil again. From now on I'll just be me.",
    "Don't worry, Leela... soon we'll be able to look on this and laugh.",
    "Dooooooo...",
    "Dream on, skintube! I'm only programmed to bend for constructive purposes. What do I look like, a debender?",
    "Dying sucks butt! How do you living beings cope with mortality?",
    "Each more identical than the last!",
    "Eh, I dunno.",
    "Eh, I've heard better.",
    "Eh, probably dead. Already dissolving in a bathtub if we're lucky.",
    "Eh, saw it coming.",
    "Eh, they're both fine choices. Whatever floats your boat.",
    "Eh.",
    "El Zilcho. Hey, is it too late to change my superhero name?",
    "Everybody was doing it... I just wanted to be popular.",
    "Everytime I burp, a new galaxy is created. Two if I've been eating broccoli.",
    "Eww!",
    "Except for 'Sports' by Huey Lewis.",
    "Falcon, this is Blue Raven. The goose has nested. Repeat, the goose has nested.",
    "Fat chance! You can't count on God for jack! He pretty much told me so Himself. Now, come on. If we don't free those monks, no one will.",
    "Final boarding call for Flight 406, non-stop service to pain! Now boarding standby passengers...",
    "Fine, we'll have rack of Nibbler.",
    "Fleeing somewhere?",
    "Flexo! What are you doing in a hazardous waste bin?",
    "Follow that guy. Ther's an extra hundred in it for you, if you follow him that close that you run him over.",
    "For one thing, we both have a tough outer shell but live a rich inner life. And also... well, you know. No, it's just... neither of us can get up when we get knocked on our back.",
    "For the love of God, somebody kick his ass!",
    "Forget it. You can't tempt me.",
    "From now on, I can bend what I want, when I want, who I want.",
    "Fry crack corn, and I don't care, Leela crack corn, I still don't care, Bender crack corn, and he is great, Take that, you stupid corn!",
    "Fry who?",
    "Fry! Fry, wake up! It's me, Bigface. Come out and groom my mangy fur.",
    "Fry's right! Let's kill the captain and order some strippers!",
    "Fry, hurry up! You're missing the dinosaurs!",
    "Fry, I'm sorry. I should have understood how someone can love an inferior creature... because I love you... not in the way of the ancient Greeks, but the way a robot loves a human, and a human loves a dog, and, occasionally, a gorilla loves a kitty.",
    "Fry, I've never asked you for anything before, but, if it's not too much trouble, when you get to the ninth round, just let him win.",
    "Fry, in order for me to get busy with maximum efficiency, I need a girl with a 400-ton booty.",
    "Fry, of all the friends I've had... you're the first.",
    "Fry, stop interfering with history! I don't wanna have to memorize a lot of new kings when I get back.",
    "Fry, throw in the towel! For God's sake, Fry!",
    "Fry, what's wrong?",
    "Funny, funny stuff.",
    "Game's over, losers! I have all the money. Compare your lives to mine and then kill yourselves.",
    "Get a room!",
    "Get it off! Get it off! Oh-oh. How many roads must a man walk down before you can call him a... Aaow!",
    "Get to the point. What does it say about me, Bender?",
    "Gimme my body back, ya two-bit thief!",
    "Give 'em hell, Morbo!",
    "Go, man, go!",
    "Good night, you princes of Maine, you kings of New New England.",
    "Good point, Bender!",
    "Good point... but here's a disturbing reminder: anyone you knew or loved in the 20th century is dead.",
    "Got a hot, steaming batch right here.",
    "Grab a shovel. I'm one skull short of a Mouseketeer reunion.",
    "Gracias.",
    "Great is good, but amazing would be great.",
    "Great, you guy are my new best friends!",
    "Green Bluebird, this is Mr. Fabulous. We are go for cheesing it.",
    "Guys, guys! Hedonismbot is finally settling down and marrying a nice house in the suburbs, but tonight, he's having the girls-gone-wildest bachelor party of all time!",
    "Guys, you'll never believe what happened! First I was God, then I met God!",
    "Halt! Who goes there?",
    "Hang on, Scruffy!",
    "Harpoon, my ass.",
    "Hasta la vista, meatbag!",
    "Have you tried gettin' her pregnant?",
    "Haven't I done enough already?",
    "He did it! And he's not looking back at that cool explosion! He's a hero!",
    "He just won't stop with the social commentary.",
    "He was coming right at us! You all saw it!",
    "He's a mad man! A mad man!",
    "He's Mexican, I'm Mexican. Let me handle this.",
    "He's pending for a bending!",
    "Hello, fellow bees. How's the abdomen? Swollen with nectar, I trust?",
    "Here it comes.",
    "Here's your Guttenberg Bible, masters, plus the Colonel's secret recipe. 'Chicken, grease, salt'.",
    "Hermes, old buddy!",
    "Hey Fry, while I'm down here you want me to smack up the corpse a little?",
    "Hey look, Bigfoot! He's back!",
    "Hey look, it's bigfoot again.",
    "Hey! Bender the Offender doesn't need YOU! Bender the Offender doesn't need ANYBODY!",
    "Hey! Don't make me go upside your head!",
    "Hey! I didn't blow up. Ass, ass, ass, ass, ass, ass, ass, ass, ass!",
    "Hey! I got a busted ass here and I don't see anyone kissing 'it'!",
    "Hey, bite my shiny metal ass.",
    "Hey, buddy. I'm looking for fresh slug.",
    "Hey, chief. You screwed up. There's nothing in here.",
    "Hey, everybody! Do the Bender. This move's called the Bender.",
    "Hey, guess what you're accessories to.",
    "Hey, I think your son might also like those boots.",
    "Hey, Kwanzaa-bot! Where you off to?",
    "Hey, let's all join the Reform party.",
    "Hey, look what I won off some tourist's pocket.",
    "Hey, Mac, where do you want those rat droppings you ordered?",
    "Hey, oh! You want me to do two things? Eh, I'd call my lawyer if dialing the phone wasn't such a hassle.",
    "Hey, other universe, bite my shiny metal ass!",
    "Hey, sexy mama... Wanna kill all humans?",
    "Hey, that guy said to tell you...",
    "Hey, that was my last beer! You bastard! I'll kill you!",
    "Hey, the blues. The tragic sound of other people's suffering. That's kind of a pick-me-up.",
    "Hey, the guy's dead! There's no law against grave robbing.",
    "Hey, these guys are all right.",
    "Hey, we're just a stone's throw from Tijuana.",
    "Hey, what's this? Hermes' dreadlocks, and his arm? Leela, I'm shocked! Food goes in the disposal, hair and flesh go in the trash.",
    "Hey, whoa! There is no way that baby is mine.",
    "Hey, whose been messing with my radio? This is not alternative rock, it's college rock.",
    "Hey, yeah! I could write a song! With real words, not phony ones like 'odelay'.",
    "Hey, yeah.",
    "Hey, you're not a fem-puter, you're a fem-bot!",
    "Hey. Do I preach at you when you're lying stoned in the gutter? No!",
    "Hey. Do I preach at you when you're lying stoned in the gutter?",
    "Hey. What are you doing with my head?",
    "Hey. What kind of party is this? There's no booze and only one hooker.",
    "Hey. You put a one and two zeros in front of that or we pass. Deal.",
    "Hi. I'm Bender, this is my robot Bender, and this is my other robot Bender.",
    "High school gym renovations on schedule? What a load!",
    "His ass-ias is gracias.",
    "His legend lives on.",
    "Hm. I forgot you could tempt me with things I want.",
    "Hmmm, it should look like this...",
    "Hmmm... okay, but I'll need ten kegs of beer, a continuous tape of 'Louie, Louie,' and a regulation two-story panty-raid ladder.",
    "Ho, ho... Ow!",
    "Hold on to your dookie. It's about to get spooky.",
    "Hold on! There's alcohol on this planet. My kegger radar is going crazy.",
    "Honey, I wouldn't talk about taste if I was wearing a lime green tank top.",
    "Honey, that thing was ruined the minute it went on you. That's what I'm talking about.",
    "Hooray! I graduated. Time to bend around Europe for a few months, then get a job bending.",
    "How 'bout a few words, Professor? I said words.",
    "How, by making me look at you?",
    "Hubba-hubba! She is built. In Mexico, I believe.",
    "I accept this Nobel Peace Prize not just for myself, but for crime robots everywhere. Skoal!",
    "I am Bender please insert girder.",
    "I am forty percent zinc.",
    "I believe that qualifies as ill, at least from a technical standpoint.",
    "I can assure you, I hardly know the meaning of the word labor.",
    "I can't believe someone sent an intergalactic spaceship to deliver a package to Atlantic City. What are we delivering, anyway?",
    "I can't go into battle. I'm a conscientious objector.",
    "I can't keep running people over. I'm not famous enough to get away with it.",
    "I can't see anything. Are we boned?",
    "I can't see what's happening. Are we boned?",
    "I didn't mean you're all fat! Just fatso over there.",
    "I didn't say I wasn't a drama queen.",
    "I didn't steal them, I bought them. I love her that much.",
    "I do!",
    "I don't 'need' to drink, I can quit any time I want.",
    "I don't blame myself. I blame all of you!",
    "I don't know what it is yet!",
    "I don't know where most of her is, but her tongue's in Zapp's mouth. Whoo, nasty!",
    "I don't know. Do you think you could survive a seven-hundred foot fall?",
    "I don't know. I only gamble with chumps.",
    "I don't know. It wasn't here when I took your umbrella.",
    "I don't remember ever fighting Godzilla... But that is so what I would have done!",
    "I don't tell you how to tell me what to do, so don't tell me how to do what you tell me to do.",
    "I don't think you realize how rich he really is. In fact, I should put on a monocle.",
    "I doubt it!",
    "I found rocks. You guys eat rocks, right?",
    "I got a good vibe from this place. Nice, long dinner table, quiet, well behaved spiders, graveyard adjacent, Yep, this is going to be... Aah!",
    "I got his wedding ring. Sorry ladies I'm taken.",
    "I guess a robot would have to be crazy to wanna' be a folk-singer...",
    "I guess I'll go too, with Leonard's permission.",
    "I hate the people who love me. And they hate me.",
    "I have reached the gateway to another universe. I feel awed and strangely humbled by the momentous solemnity of this occasion.",
    "I have some new elements to create. Better cover your nads. It's about to get non-Newtonian in here.",
    "I hocked it.",
    "I hope he didn't die. Unless he left a note naming me his successor, then I hope he did die.",
    "I hope it was one of my enemies. Those guys suck.",
    "I know, right?",
    "I like it here. I have wealth, fame, and access to the depths of sleaze that those things bring.",
    "I love you meatbags!",
    "I meant ass whiplash!",
    "I need professional help, and damn the expense!",
    "I never made anyone's life easier, and you know it!",
    "I read the script, and I think it would help my character's motivation if he was on fire.",
    "I said shut up!",
    "I say the world must learn of our peaceful ways... by force!",
    "I support and oppose many things, but not strongly enough to pick up a pen.",
    "I swear those are prescription. I need them for reading stuff... on the other side of stuff.",
    "I think that qualifies as ill, at least from a technical standpoint.",
    "I think you misunderstood the concept of 'benderin' time.'",
    "I thought I killed you, my best friend.",
    "I thought that was number two!",
    "I was a hero to broken robots 'cause I was one of them, but how can I sing about being damaged if I'm not? That's like Christina Aguilera singing Spanish. Ooh, wait! That's it! I'll fake it!",
    "I was built ready! Gimme the bell! Gimme the bell!",
    "I was enjoying it until you guys showed up.",
    "I was God once.",
    "I was having the most wonderful dream. I think you were in it.",
    "I was not just a blast. It was a celebration of the accomplishments of my past prototypes, which just happened to take the form of a drinking contest.",
    "I was telling Fry you were dead so that he would cry out the emperor, but you had to spoil it by surviving.",
    "I was thinking Benderbrau if it's an ale, Botweiser if it's a lager.",
    "I'd like to give Robot 1-X a big smooch on the... Hey! What's the dilly-o?",
    "I'll call him Ben, after the first half of me, Bender.",
    "I'll do it when we get back.",
    "I'll give you 300 bucks for it.",
    "I'll have to check my program.",
    "I'll make you cry, buddy. You're a pimple on society's ass and you'll never amount to anything.",
    "I'll put on my tutu.",
    "I'll save me.",
    "I'll save you, Professor, Zoidberg and Leela!",
    "I'll say. Whooooo!",
    "I'll tell you who I remember. Enupsis! Pleotut! Whatsisname! He was the greatest of all.",
    "I'll tell you, with my final breath. I came here with a simple dream: a dream of killing all humans. And this is how it must end? Who's the real seven billion ton robot monster here? Not I. Not... I.",
    "I'm a bender. I bend girders, that's all I'm programmed to do.",
    "I'm a big robot, and I want a big cereal!",
    "I'm a thing.",
    "I'm at the end of my rope. I can't live another minute without poor, sweet Nibbler.",
    "I'm back! Everyone at Kinko's was an idiot, so I brought the original.",
    "I'm Bender, baby! Please insert liquor!",
    "I'm Bender, the lovable rascal!",
    "I'm bored. Let's drink!",
    "I'm forty percent ass.",
    "I'm gonna be the greatest Ultimate Robot Fighter ever! Float like a floatbot, sting like an automatic stinging machine.",
    "I'm gonna die! That's the exact opposite of what I want!",
    "I'm in!",
    "I'm not allowed to vote.",
    "I'm not an idiot, so yes, absolutely.",
    "I'm plenty generous. What about that time I gave blood.",
    "I'm really starting to swell up with beer. I must look ridiculous.",
    "I'm so full of luck, it's shootin' out like luck diarrhea.",
    "I'm so lonely. I'm gonna go eat a bucket of ice cream.",
    "I'm telling you, Fry, they've got a chat room for everybody... and here it is!",
    "I'm the first one to work. A new low.",
    "I'm thinking of buying a yacht to house my thoroughbreds. How am I supposed to do that without smoking a cigar?",
    "I'm tryin' but he's not makin' it easy.",
    "I've been married to worse.",
    "I've got fame, money, groupies, and it's all thanks to being completely immobilized.",
    "If I'm not going to catch a fish, I might as well not catch a big fish.",
    "If it ain't black and white, peck scratch, and fight!",
    "If it's chicken, chicken a la king. If it's fish, fish a la king. If it's turkey, fish a la king.",
    "If only somehow, some way... he and I could drive to Vegas pick up some floozy-bots and void their warranties all night long! Whoo!",
    "If there's anything I know about fox hunting, it's everything about it.",
    "Impending para un bending!",
    "In a closet? Oh humans...",
    "In here is the only place I'm not. Mwa-ha-ha-ha! Mwa-ha-ha-ha! I amuse myself.",
    "In the name of all that is good and logical, we give thanks for the chemical energy we are about to absorb. To quote the prophet Jerematic, one-zero-zero-zero-one-zero-one-zero-one-zero-one-zero-one...zero-one-zero-one-one-zero-zero-one... two. Amen.",
    "In this case, small. Woooo!",
    "Interesting. No, wait. The other thing. Tedious.",
    "Is he any good?",
    "Is it within city limits?",
    "Is that some sort of attack mushroom or just a moldy schnauzer?",
    "Is the Space Pope reptilian?",
    "It ain't easy. It just proves how great I am.",
    "It called me what?",
    "It can, and for all you know, it is.",
    "It is if you're a laser printer.",
    "It truly has. My romance with Calculon has shown me a lot about myself.",
    "It wasn't a bird's nest falling. That sounds like this.",
    "It's 'vortices,' meatbag!",
    "It's benderin' time!",
    "It's hopeless! Abandon ship!",
    "It's hopeless. We might as well turn in my head for the five cent deposit.",
    "It's like fine cognac with a hint of aged scrotum.",
    "It's not about the money, Nixon, though I'd like much more. It's 'cause Leela's a threat. A threat to my reputation. She's committed 30 felonies in 12 star systems. If no one stops her, she'll break my record for longest rap sheet.",
    "It's not ironic, it's just mean. Take this!",
    "It's not small?",
    "It's salt with water in it, if that's what you mean.",
    "It's used to it. Woooo!",
    "It's what made me me.",
    "Je suis Napoleon! Ha ha ha! No, seriously, I'm not.",
    "Just ask Flabby over here to describe it to you later.",
    "Just like at the movie theater. Wooo!",
    "Just like inside me, I've got the heart of a human.",
    "Just tell us what's happening!",
    "Keep 'em to yourself, pops.",
    "Kill all humans, kill all humans, must kill all hu...",
    "Ladies and gentlemen of the jury... Oops! Sorry. Force of habit. I support this proposition because I'm in love with a goopy, flesh-and-blood woman, and not surprisingly, she loves me. This is a simple matter of justice, which I'm not normally for. So please, vote yes. After all, our love isn't any different than yours, except it's hotter, 'cause I'm involved.",
    "Learning is fun.",
    "Leela's right, fishing blows. What do we say we make it interesting? Everyone kick in five bucks. Now, wasn't that interesting?",
    "Leela, save me! And yourself, I guess... and my banjo... and Fry.",
    "Leela, you gotta help me.",
    "Legion of Benders, come unto me! We have one thing to do.",
    "Let a whole new wave of cruelty wash over this lazy land!",
    "Let's commence preparations for rumbling!",
    "Let's face it, comedy is a dead art form. Now tragedy, ha ha ha, that's funny.",
    "Let's just say he might not make it to 'The Last Supper'.",
    "Let's just say I lucked out at the track. Also, I rigged one race.",
    "Lick my frozen metal ass.",
    "Like everything in life, pumping is just a primitive, degenerate form of bending.",
    "Like putting too much air in a balloon!",
    "Like whale barf.",
    "Listen to me, Leela. I'm an expert at not caring. The secret is to stop giving a rat's ass about anyone else and start thinking of the things that you want, that you deserve, that the world owes you.",
    "Listen up, everyone! I have a dramatic speech. Cameraman, camera on me! Director, what's my motivation?",
    "Listen, you fat internet nerd!",
    "Looking at one's cards is a crutch for players who rely on skill.",
    "Looks like things are looking up.",
    "Madame, I believe you're mistaken.",
    "Make it a double!",
    "Make it zero and you've got a deal.",
    "Man, Father Time really took a bat to this place.",
    "Man, I guess it's harder than I thought to make someone cry.",
    "Man, the future's a total craphole, and whoever lives here is a crap-faced sack of crap! No offense, fellas.",
    "Mars Vegas, the eternal city.",
    "Maybe blasting this quadrant of space into a hellstorm of flaming nothingness will cheer me up a little.",
    "Maybe you can interface with my ass by biting it.",
    "Me too...",
    "Mmm hmm.",
    "Mmmm... shorts...",
    "More like Tax-a-ffusechets.",
    "My ass is about to project something.",
    "My backup unit makes a backup copy of me every day, so if something happens to my body, I just download that copy into another body. I'm immortal, baby!",
    "My brain is no match for your Von Braun.",
    "My dreams are over before they began!",
    "My God. I'm overcome with feelings. I'm experiencing a powerful yearning to... to cram my gullet full of mackerel heads.",
    "My story is a lot like yours, only more interesting 'cause it involves robots.",
    "My what, now?",
    "Nah, I'm trying to watch my input. I need plenty of wholesome nutritious alcohol. The chemical energy keeps my fuel cells charged.",
    "Nah.",
    "Naw, she'll probably make me do it.",
    "Never!",
    "New crew? Well, what happened to the old crew?",
    "New York is so burned.",
    "New? What sweater? I came in with this! I don't know you people!",
    "Nine, ten, a big fat hen.",
    "No batter! No batter! No batter anymore.",
    "No doubt about it. This place must be haunted.",
    "No friends.",
    "No I didn't. Raise middle finger.",
    "No it isn't. I just took some pictures of your face and stuck them on someone else's body.",
    "No liquor? Do svidanya, comrade.",
    "No one insults the turtles!",
    "No one! Your momma! Shut up! Take your pick.",
    "No one, baby. Lucy Liu is the only woman for Bender.",
    "No poison for us, thanks. I'll stick with good-old mineral oil.",
    "No shklit.",
    "No! Don't come in!",
    "No! I sold my body.",
    "No! I want to live! There's still so many things I don't own!",
    "No! It's called parenting.",
    "No, convicted felon.",
    "No, I was tellin' you not to worry. I'm not allowed to sing - court order.",
    "No, I'm Bender. We met once, remember?",
    "No, it's inhabited by robots.",
    "No, of course not! It was, uh... porno! Yeah, that's it!",
    "No, thanks.",
    "No, they fixed it 900 years ago.",
    "No, wait! I'm the good Santa! I've got toys at very reasonable prices!",
    "No, wait. I know these guys. They got nothing.",
    "No, we're not, you little bedwetter. Oops! I'm sorry.",
    "No. The cat shelter's on to me.",
    "Nooo, it's Fry who's crazy in this one!",
    "Nope.",
    "Nope... Aw!",
    "Not enough room? My place is 2 cubic meters and we only take up 1.5 cubic meters. We've got room for a whole nother 2/3rds of a person.",
    "Not even sauteed in a little mud?",
    "Not so neutral now, are you, Sweden?",
    "Not this one. He blew his life savings on lottery tickets.",
    "Nothing but crumpled porno and Ayn Rand.",
    "Nothing like a warm fire and a super soaker of fine cognac.",
    "Now I can explain that!",
    "Now I'm worried I'm not as smart as Leela, but at the same time, I feel relieved I'm cuter than her.",
    "Now that's acting. Calculon really Shatnered the hell out of that scene.",
    "Now you know why I used the qualifier 'practically'.",
    "Nu-uh, because in case you didn't know, I'm a robot.",
    "Nyah-nyah, we can go...",
    "O' cruel fate, to be thusly boned! Ask not for whom the bone bones - it bones for thee.",
    "Obviously not, or I'd be strangling you right now.",
    "Of course I do, right now I feel sorry for you.",
    "Of course not. A girl that fine you gotta romance first.",
    "Of course they go unheeded! How am I supposed to hear prayers coming out of my ass?",
    "Of course. Bender is a lone wolf, a solitary eagle...",
    "Of course. I'm a bender. I went to Bending College, I majored in Bending.",
    "Of course.",
    "Og. Gorilla Emperor of Earth.",
    "Oh come on!",
    "Oh my god! I just felt it ferment!",
    "Oh no you didn't!",
    "Oh! Ooh! Ow! Ooh!",
    "Oh, all right. I'll just take these $300 burglar's tools then.",
    "Oh, come on, you lazy jerks! If we all pitch in, we each only have to do one-quintillionth of a thing.",
    "Oh, crap! I'm some sort of robot!",
    "Oh, crap! It's a miracle!",
    "Oh, Elzar, everything is so good!",
    "Oh, fine. I'll get you some stupid food.",
    "Oh, how I wish I could believe or understand that!",
    "Oh, I can't stay mad at what is essentially me.",
    "Oh, man. What's the use of living if I can't say ass?",
    "Oh, merciful Poseidon. Have pity on this mechanical mariner.",
    "Oh, my God! Oh, my God! It's Elzar, the TV chef! Oh, kill me now, people!",
    "Oh, no room for Bender, huh? Fine! I'll go build my own lunar lander, with blackjack and hookers. In fact, forget the lunar lander and the blackjack. Ahh, screw the whole thing!",
    "Oh, no! I forgot this is a hoverbridge!",
    "Oh, no, they've killed me! Put me in my Sunday best and stick me in a box. Now they're lowering me into the cold, cold ground. Oh, here come the worms! Ha ha ha ha!",
    "Oh, so this is suddenly all about you! Sheesh!",
    "Oh, so we can stay in the future you like, but not the future I like? Next!",
    "Oh, sure. Let the robot do all the work.",
    "Oh, yeah? Maybe that's him in a costume.",
    "Oh, yeah? Well, bite my shiny, metal... Ohh, noooo!",
    "Oh... I think I got whiplash.",
    "Oh... Now this guy had taste.",
    "Oh... your... God!",
    "Ohhh yeahhh...",
    "OK kids, it's 9, you know what that means, Daddy's sick of looking at you so go to bed.",
    "Ok, ok. We get the point.",
    "Okay, everyone! Come and get it!",
    "Okay, Fry, grab a Kleenex for this one, 'cause there's no god and your idiotic human ideals are laughable. Ha ha ha!",
    "Okay, we won't eat you.",
    "Old New York, the city that inspired a casino in Las Vegas.",
    "On the count of three, you will awaken feeling refreshed, as if 'Futurama' were never cancelled by idiots and then brought back by bigger idiots. One... two...",
    "On the fourth day of Xmas, I stole from that lady. And a slipper on a shoe tree.",
    "Once I overclock this processor, I'll be all 'You a big dummy, Einstein! Get a haircut!'",
    "Once, when I took those hostages.",
    "One hundred dollars.",
    "One thing she can do is lodge a ball in the dead center of your brain. You better get a batting helmet.",
    "Only one way to find out...",
    "Only Robanukah, the two holiest weeks in the robot calendar.",
    "Ooee!",
    "Ooh! Dibs on his CD player!",
    "Ooh! Name it after me!",
    "Ooh!",
    "Ooh, a case of strawberry champagne. Don't mind if I do.",
    "Or a guy who burns down a bar for the insurance money.",
    "Others however will call me the World's Sexiest Killing Machine, that's fun at parties.",
    "Othewise I can't die?",
    "Ouch-o!",
    "Overruled! The choice of champions is Pabst Blue Robot.",
    "Ow-ow-ow! Ow-ow-ow! Ow-ow-ow-ow-ow!",
    "Pansy.",
    "Perfect!",
    "Pervert.",
    "Philip?",
    "Please! He's no different from the rest of you organisms. Shooting DNA at each other to make babies. I find it offensive!",
    "Please. I'm scared.",
    "Posers! I was hating Zoidberg before it was cool.",
    "Probably not, but I love you!",
    "Problem solved. You two fight to the death, and I'll cook the loser.",
    "Professor, make a woman out of me.",
    "Put it there, pal! I meant your wallet.",
    "Really?",
    "Red-hot glowing ass? I'll be right back.",
    "Rest in hell, Crapville!",
    "Ro-mance.",
    "Robo-American Studies.",
    "Robot gets bored and kills Fry with a hammer! I'm sorry. Go on.",
    "rrrr... it's so cold, my processor is running at peak efficiency!",
    "Same reason you hocked your teeth.",
    "Santa's right. We need some sort of robot.",
    "Say what?",
    "Say, buddy. Why is this grand cigar so pricey?",
    "Screw that!",
    "Second place? That's a fancy word for losing.",
    "Shield your eyes! It's like Edward James Olmos on Imax!",
    "Shinier than yours, meatbag!",
    "Shut the hell up!",
    "Shut up and pay attention to me, Bender! Look, I love life and its pleasures as much as anyone here, except perhaps you, Hedonism Bot. But we need to be shut off! Especially you, Hedonism Bot.",
    "Shut up! I said it first!",
    "Shut up, baby, I know it!",
    "Shut up, baby. You love it.",
    "Shut up.",
    "Si!",
    "Single female lawyer, Fighting for her client, Wearing sexy mini-skirts, And being self-reliant. Hey, I'm pretty good.",
    "Sir, I volunteer for a suicide mission.",
    "So can I keep the check?",
    "So do you know I'm going to do something before I do it?",
    "So does my butt, but I don't frame it and put it on the wall. Although...",
    "So if I die...",
    "So it's a cake you want, is it? I'll make you a cake you'll never forget!",
    "So that's where my cigar was.",
    "So this is what a human body feels like. Hey, where's my antenna? Oh, here it is. It just moved. But I'm not getting any reception. Maybe if I wiggle it a little...",
    "So we can have the diamond?",
    "So we're in international waters?",
    "So what could have caused that leak? A heat fracture, on account of I'm so hot?",
    "So what you're saying is that their souls were stolen?",
    "So what's the deal? And I'll take my answer in any form except a song.",
    "So, baby, what'll it be? My place or you?",
    "So, uh, what time d'you close tonight?",
    "So? It's not like it's the only one we've got.",
    "So? It's not like you slept with him.",
    "Some guy's.",
    "Someone fat get in my way!",
    "Something tells me I could easily beat those trained professionals.",
    "Sorry I got you sent to that South American Turkish prison instead of me on account of mistaken identity.",
    "Sorry, buddy. Here you go.",
    "Sorry, it's not quite finished.",
    "Sounds boring.",
    "Stay away from our women! You've got metal fever, boy! Metal fever!",
    "Stinking bureaucrats. I hate 'em!",
    "Stop that tenderizing! Prepare for a benderizing!",
    "Stop thinking, Fry!",
    "String him up!",
    "Stupid anti-pimping laws. Well, pay the man!",
    "Stupid can opener! You killed my father, and now you've come back for me!",
    "Stupid jerks won't let me stay in the good future.",
    "Sucker.",
    "Sure, I can help you, but we might have to metaphorically make a deal with the devil, and by 'devil', I mean Robot Devil, and by 'metaphorically', I mean get your coat.",
    "Sure, why not?",
    "Sweet photons. I don't know if you're waves or particles, but you go down smooth.",
    "Tell me, have things changed on the outside? Is food finally in pill form? What about pills? Are they in food form?",
    "Th-th-that's all you get, chumps!",
    "Thank you, and good night.",
    "Thank you.",
    "Thanks a lot, Takei. Now everybody knows.",
    "Thanks. And call me Bender.",
    "That dirty, double-crossing bastard! How dare he run off with Richard Nixon?",
    "That galaxy is signaling in binary. I should signal back, but I only know enough binary to ask where the bathroom is. You speak English?",
    "That I, Bender, am perfect for the part.",
    "That is so wrong! You can't melt down broken robots, not right when they're kissing my ass!",
    "That painting! The eyes are watching me!",
    "That plot makes perfect sense. Wink, wink.",
    "That professor guy? That crawfish thing? This stinks! I demand a hero's welcome after 72 network episodes!",
    "That Twizzler!",
    "That'll be easy. I never wear the damn thing.",
    "That'll take care of those annoying rats, now to bake a cake so delicious they'll have no choice but to love and worship me!",
    "That's a complete load!",
    "That's basically what I do every day.",
    "That's for sure, not on the measly salary I steal from you every week.",
    "That's impossible!",
    "That's L.A. for you.",
    "That's my bastard!",
    "That's no flying saucer. That's my ass!",
    "That's no lady.",
    "That's not an issue for us. We're wildlife.",
    "That's right baby, I ain't your loverboy Flexo, the guy you love so much. You even love anyone pretending to be him.",
    "That's right! I'm sober and crazy, and I don't know what I might do!",
    "That's right, we want some money.. wait, what's this about Fry?",
    "That's the great thing about that hand.",
    "That's what Fry said when we turned on the debate.",
    "That's what I'm calling the yacht.",
    "That's what makes it so nasty.",
    "That's what she said. Whooooo!",
    "That's what they said about being alive!",
    "That's why I'll be proud to go up on stage tomorrow and say, 'Look at me, world! I am a broken robot!'",
    "The decaying ruins of old New York. Welcome home, buddy.",
    "The fact is, humans are completely harmless.",
    "The grown-ups have to talk.",
    "The important thing is, by my standards, I won fair and square. Now, who wants brunch, cooked with plenty of 'confidence'?",
    "The last 'human' ghost. But robot ghosts... Oooh!",
    "The name's Bender.",
    "The only reason you get all the guys is because you dress like a tramp!",
    "The other place had a lot of nice things too. Did you even see that mountain of skulls?",
    "The pie is ready. You guys like swarms of things, right?",
    "The truth is often stupid.",
    "The world? That's where I live! See, I told you I was in there.",
    "Then lose some weight!",
    "Then why aren't you fixing the boiler?",
    "Then why do I have to be careful?",
    "There was nothing wrong with that food. The salt level was 10% less than a lethal dose.",
    "There's a dam.",
    "There's no backup copy of me?",
    "There's nothing wrong with murder, so long as you let Bender wet his beak.",
    "There, now no one will be able to say I don't own John Larroquette's spine.",
    "There. Now no one will forget how I lived or my attitude regarding butt.",
    "There. This'll teach those filthy bastards who's lovable.",
    "These balls are making me testy! If they don't stop bouncing and jiggling, I swear I'm gonna shove this treaty up their... Wait a minute, where do you shove things up a ball?",
    "These balls are making me testy!",
    "They are bronze.",
    "They don't look so lucky to me.",
    "They look like dorks!",
    "They make me look cool.",
    "They say you can judge a man by the company he keeps. So here is the professor's oldest friend, a grotesque, stinking lobster.",
    "They're giving out the minor technical awards. I think they're up to Writing.",
    "They're my booties from when I was a kid.",
    "They're my lucky shades. I got them off some lucky guy while his lucky seeing-eye dog was out taking a whiz.",
    "Third place? This is the greatest injustice Germany has ever committed!",
    "This calls for a party, baby. I'm ordering a hundred kegs, a hundred hookers, and a hundred Elvis impersonators who aren't above a little hooking, should the occasion arise.",
    "This comes as quite a shock. Then again, this is not surprising in the least.",
    "This could mean the end of the banana daiquiri as we know it! Also, life.",
    "This guy's too trustworty. What's his angle?",
    "This is awful. Somewhere there's a more evil Bender than me. I do my best, dammit!",
    "This is great! My buddy's alive, and his credit cards are valid again! Let's go get hammered!",
    "This is the Brooklyn bound B-train , making local stops at wherever the hell I feel like. Watch for the closing doors. Bim-bum!",
    "This is the worst kind of discrimination. The kind against me.",
    "This last week with Fry has been great. Beneath his warm, soft exterior beats the cold, mechanical heart of a robot.",
    "This looks like a good place to ditch some evidence.",
    "This outfit makes me look fat. Is it trampy to go on a first date nude?",
    "This seems like a nice future. Let's just stay here. We can settle down on that mountain of skulls. Hey! That place had a gorgeous view of Blood Lake.",
    "This time, I miss Nibbler, and I'm feeling nosy and opinionated.",
    "Those are waves, jackass! It's supposed to be a river!",
    "Those could be anyone's thoughts, fat-ass.",
    "Those times I was slightly on my side.",
    "Time heals all wounds.",
    "Time? I can't go back there!",
    "Told you.",
    "Too bad it's a dump.",
    "Too late this is more fun",
    "Too late, this is more fun.",
    "Too much work. Let's burn it and *say* we dumped it in the sewer.",
    "Translation. boring.",
    "Two hundred thousand and one?",
    "Ugh! Gageth me with a spoon.",
    "Uh, can people who hate 'Star Trek' leave?",
    "Uh, fifty-sixish?",
    "Uh, hey, buddy! Yo! You mind taking your head off?",
    "Uh, me no speak-a the English.",
    "Uh, nothin'!",
    "Uh-oh jealousy!",
    "Uh-oh. I don't like the sound of that.",
    "Uh-oh.",
    "Umm, is this the boring, peaceful kind of taking to the streets?",
    "Up your face! Ahahahaha.",
    "Up yours, bimbo!",
    "Vamonos!",
    "Wah, wah! Baby wants a Zima!",
    "Wait a minute. Aren't you a member of the yacht club?",
    "Wait a minute...",
    "Wait! As men of science, are not your minds open to new ideas? I say, 'Do not judge me, until you have tried my way of life for yourselves.'",
    "Wait! I'm not in position!",
    "Wait, let me come with you.",
    "Wait, my cheating unit malfunctioned. You gotta' give me a do-over.",
    "Was it poorly Xeroxed?",
    "Was that before or after you slept with him?",
    "We all feel like that all the time. You don't hear us gassing on about it.",
    "We can hide in here. It's free on Tuesdays.",
    "We could sing.",
    "We live to suck another day.",
    "We pollute too much. We're destroying the world and killing the turtles.",
    "We'll soon stage an attack on technology worthy of being chronicled in an anthem by Rush!",
    "We're at finger alert five, people.",
    "We're back, baby!",
    "Well, all right, but I don't want anybody thinking we're robosexuals so if anyone asks, you're my debugger.",
    "Well, all right. But I don't want anyone to think we're robosexual or anything, so if anyone asks, you're my debugger.",
    "Well, at least I don't have the hiccups any more, what's up?",
    "Well, everyone, prepare to have your guts kicked out by folk singers.",
    "Well, I can't do it. It so happens tomorrow is a robot holiday.",
    "Well, I do think of human life as expendable.",
    "Well, I love a challenge. Um... no... I've got it. I'm gonna be completely honest with you, Planet Express ship. Those women you saw me with were my accountants.",
    "Well, I wasn't built to steal Leela's purse either, but that didn't stop me.",
    "Well, I'll shoot her with my ray gun when she comes, Yes, I'll shoot her with my ray gun when she comes, Yes, I'll shoot her with my ray gun, Oh, I'll shoot her with my ray gun, Yes, I'll shoot her with my ray gun when she comes, When she comes! I'll be blastin' all the humans in the world, I'll be blastin' all the humans in the world, I'll be blastin' all the humans, I'll be blastin' all the humans, I'll be blastin' all the humans in the world, In the world!",
    "Well, I'm glad we got all that out in the open. We'll just let ourselves out.",
    "Well, I'm rich. Goodbye, losers whom I always hated!",
    "Well, if jacking on will make strangers think I'm cool, I'll do it.",
    "Well, it was nice meeting you Fry. I'm gonna go kill myself.",
    "Well, life goes on... except for you. Ha ha ha ha!",
    "Well, my normal fee is 500, but seeing that it's for you, I'm gonna need it in advance.",
    "Well, obviously I need floozies.",
    "Well, step one, I had to lift the lid. That was the first little annoyance. Am I right, men?",
    "Well, they should have stop making her about halfway through.",
    "Well, we're boned.",
    "Well, we're in Tijuana. I wanna live a little.",
    "What a cheesy effect.",
    "What a waste.",
    "What about in the gutter?",
    "What comes out one end we feed to the other. Also Indian food.",
    "What do I look like, a debender?",
    "What do ya got there, numbers?",
    "What do you mean 'we', mammal?",
    "What does it matter? I'll never be a Globetrotter. My life, and by extension, everyone else's, is meaningless.",
    "What have I done?",
    "What is it with you kids? Every other day, it's food, food, food.",
    "What is that fat, ugly thing? A frog? A toad? Or your momma?",
    "What is that? One of those Led Zeppelins I've heard so much about?",
    "What is the world coming to? That Fry is a sicko poivert, I tell ya! Dating a robot... it's an attrocimacy!",
    "What to do, what to do. One 300 dollar hookerbot or 300 one dollar hookerbots?",
    "What up?",
    "What was the first one again?",
    "What what?",
    "What's that black cracker?",
    "What's that weird cat thing?",
    "What's that, sonny? You say it'll put some whoopee in my cushion?",
    "What's the matter? Did someone die or something?",
    "What's wrong, Big Boots?",
    "What-mas?",
    "What?... What?",
    "Whatever.",
    "When I grow up, I wanna be a steam shovel!",
    "When will man learn that all races are equally inferior to robots?",
    "Where are we delivering it?",
    "Where are we? The ass?",
    "Where are you going to stay?",
    "Where would the professor be without students who love and respect him? Right there! Ha ha ha ha!",
    "Who *could* do such a thing? And by that I mean this.",
    "Who are you, and why should I care?",
    "Who invited you? Let's just see 'All My Circuits The Movie.'",
    "Who the hell is he?",
    "Who wants some dolphin?",
    "Who will make Bender waffles just the way he likes them now?",
    "Who's in charge of this dump?",
    "Whoa!",
    "Whoa, whoa! I love partying as much as the next fellow, but this is Oktoberfest. Good day to you, sir.",
    "Whoops.",
    "Why don't you just use a potted plant like Fry?",
    "Why, 'cause I can make annoying noises?",
    "Wiggles, weren't you about to propose a toast to your gallant captain?",
    "Woo! I'll just cut that...",
    "Woof. If that stuff wasn't real, how can I be sure anything is real? Is it not possible - nay, probable - that my whole life is just a product of my or someone else's imagination?",
    "Woooo!",
    "Word!",
    "Work his gut. I like it tender.",
    "Worshipers? This ought to liven up my endless tragic voyage.",
    "Wouldn't it make sense to weld everyone except me to the wall?",
    "Wow! I'm finally gonna see my favourite chef, TV's Elzar! Aww, this is the greatest nanosecond of my life! No, this one is! No, this one. Wait! That one was... slightly worse. Ah! So far so good on this one!",
    "Wow! Neat! Mind if I try that again?",
    "Wow, that lady's got a huge ass.",
    "Wow, your kid is great. How hard did you say you had to hit him?",
    "Yahoo! Another thing I'm great at. Wait, why'd you stopped eating, master?",
    "Yeah! Now, are you gonna come to the squid fights with us or sit here wallowing in your prehistoric junk?",
    "Yeah, and this beer can is made out of old robots.",
    "Yeah, but the rents are outrageous.",
    "Yeah, doing crap work. Robots are only working as bat boys, ball polishers and sprinkler systems. But how many robot managers are there?",
    "Yeah, I mean one cantaloupe-sized bloodshot eye?, you ain't winning no beauty pageants, lady.",
    "Yeah, if you're into grey dust.",
    "Yeah, like you don't have crap in your neck.",
    "Yeah, right! What's he gonna do, break my legs?",
    "Yeah, we're back.",
    "Yeah, well... I'm gonna go build my own theme park, with blackjack and hookers. In fact, forget the park!",
    "Yeah, what he said! It's a mutiny led by Fry!",
    "Yeah, why is it so important to you?",
    "Yeah, why is it so important you?",
    "Yeah, yeah, either one's fine.",
    "Yeah, yeah. I can take a hint.",
    "Yeah. And if you won't give me another chance perhaps you'd give one to...",
    "Yeah. Anyone who misses it will regret it the rest of his life. Hey, Fry. Could you go make us some popcorn?",
    "Yeah. Food was good, though.",
    "Yeah. What are you, chicken?",
    "Yeah? Could a big, hallucinating baby do this?... Wah-ha-ha! I'm scared!",
    "Yep, mind-numbingly interesting.",
    "Yep. My full name is Bender Bending Rodriguez.",
    "Yep.",
    "Yes! In your face, Gandhi!",
    "Yes! Nailed it!",
    "Yes, sir! Good one, sir!",
    "Yes, we have to work together, and not have this fight I was definitely winning.",
    "Yes. Although a robot would have to be crazy to be a folk singer.",
    "Yes. I joined the club I thought was cool. But it turned out all leaguee-weegies are totally lame. That's what we call ourselves. Leaguee-weegies.",
    "Yo, Captain Catarats. Why are we stopping here?",
    "Yo, old guy. Why do we need to use those tiny microdroids? Can't you just shrink us?",
    "You a big dummy!",
    "You bastard!",
    "You call that a couch? I demand a pillow!",
    "You call that motivating me? Don't just whip with your arms. The power comes from your hips. Like this.",
    "You can't tell me what my son can and cannot do! You may know what's in his head, but not what's in his heart.",
    "You could drop dead. That would show them.",
    "You degenerate hussy! I'm disappointed in you too, Anglelyne.",
    "You didn't stick your landing!",
    "You got it!",
    "You guys realize you live in a sewer, right?",
    "You had a life before you met me? Really?",
    "You humans are afraid of a little robot competition. You would never let a robot on the field.",
    "You know its funny...",
    "You know we don't!",
    "You know what always cheers me up? Laughing at other people's misfortune. Hahaha!",
    "You know, a coward.",
    "You know, like how I live every day.",
    "You know, playing you all for chumps?",
    "You know, when I first got broken, I thought my life was over. But look at me now.",
    "You mean Space Tax-achusetts? No chance, judge-pants! We're gonna fight to legalize it right here!",
    "You mean your wheelchair?",
    "You never ask me if I'm okay. I'm feeling a little neglected here.",
    "You really are too picky.",
    "You really want a robot for a friend?",
    "You seem a tad wound up, buddy. And your face is greasy. Real greasy. You been up all night?",
    "You think robot life is worth less than human life, don't you?",
    "You think robots care what some hack science-fiction writer thinks? I killed Isaac Asimov on the way over here. Well, Isaac 'some'body.",
    "You think you're so hot!",
    "You were looking up curse words in the dictionary. It seemed like a better use of your time.",
    "You wore the same pants for a thousand years? No wonder they made a run for it.",
    "You're better off dead, I'm tellin' you, dude.",
    "You're drunk, Fry. This is the elephant detector. I just set it to big and woolly.",
    "You're screwier than my Aunt Rita, and she's a screw.",
    "You're the kind of guy who visits Jerusalem and doesn't want to visit the Sexeteria.",
    "You're twice the the he ever was.",
    "You're watching Futurama... the show that does not advocate the cool crime of robbery.",
    "You're with me now! This is the maximum level of being with me!",
    "You've convinced me life is worth living... by showing me how bad my funeral will suck!",
    "You, sir, have defaced a national treasure! I demand that you restore my buttocks to their former glory.",
    "Your basic human is between three and twenty-five feet tall, and is mostly composed of an oily goo wrapped in a t-shirt.",
    "Your best is an idiot!",
    "Your company promotes wrong love. If you don't shut down right now, the only thing wired about you will be your jaw!",
    "Your loss. Hey, Professor! You're my wingman.",
    "Your social security check's bounced. Stuff cost more than it used to. Young people use curse words.",
    "Your wiener! ha ha",
    "Zoidi-poo...",
    "zzzzz... Kill all humans... zzzz... Kill all humans..."
]
